version: 2.1

description: |
  Python code quality automation for Branch Butler.

  Provides commands and jobs for formatting, linting, static analysis,
  and automated PR reviews. Includes slash command support for
  interactive PR workflows.

  Commands:
    - install-tools: Install pinned versions of quality tools
    - format: Auto-format with Black and isort
    - lint: Comprehensive linting with pylint, flake8, mypy, bandit
    - danger: Automated PR review
    - rebase: Smart rebasing with conflict resolution

  Jobs:
    - code-quality: Full quality suite with caching
    - pr-review: Automated PR review workflow

display:
  home_url: "https://branchbutler.com"
  source_url: "https://github.com/branchbutler-labs/python-quality-orb"

# Import executors
executors:
  python:
    description: <<include(executors/python.yml)>>
    parameters: <<include(executors/python.yml)>>
    docker: <<include(executors/python.yml)>>
    resource_class: <<include(executors/python.yml)>>
    environment: <<include(executors/python.yml)>>
    working_directory: <<include(executors/python.yml)>>

# Import commands
commands:
  install-tools: <<include(commands/install-tools.yml)>>
  format: <<include(commands/format.yml)>>
  lint: <<include(commands/lint.yml)>>
  danger: <<include(commands/danger.yml)>>
  rebase: <<include(commands/rebase.yml)>>

# Import jobs
jobs:
  code-quality: <<include(jobs/code-quality.yml)>>
  pr-review: <<include(jobs/pr-review.yml)>>

# Usage examples
examples:
  basic-formatting:
    description: Basic code formatting with auto-commit
    usage:
      version: 2.1
      orbs:
        python-quality: branchbutler-labs/python-quality@1.2.0
      workflows:
        format-code:
          jobs:
            - python-quality/code-quality:
                run-format: true
                run-lint: false
                auto-commit: true

  full-quality-check:
    description: Complete code quality check with formatting and linting
    usage:
      version: 2.1
      orbs:
        python-quality: branchbutler-labs/python-quality@1.2.0
      workflows:
        quality-check:
          jobs:
            - python-quality/code-quality:
                line-length: 100
                lint-fail-on-error: true
                auto-commit: false
                context: branchbutler

  pr-automation:
    description: Automated PR review workflow
    usage:
      version: 2.1
      orbs:
        python-quality: branchbutler-labs/python-quality@1.2.0
      workflows:
        pr-workflow:
          jobs:
            - python-quality/code-quality:
                filters:
                  branches:
                    ignore: main
            - python-quality/pr-review:
                requires:
                  - python-quality/code-quality

  custom-command:
    description: Using individual commands in custom jobs
    usage:
      version: 2.1
      orbs:
        python-quality: branchbutler-labs/python-quality@1.2.0
      jobs:
        my-custom-job:
          executor: python-quality/python
          steps:
            - checkout
            - python-quality/install-tools:
                install-formatters: true
                install-linters: true
            - python-quality/format:
                line-length: 120
                auto-commit: true
            - python-quality/lint:
                fail-on-error: true
      workflows:
        main:
          jobs:
            - my-custom-job
